server:
  port: 8006


spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 129.211.28.174
      port: 8500
      discovery:
        service-name: ${spring.application.name}